VENDOR=samsung
DEVICE=quincydcm
OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/$DEVICE-vendor-blobs.mk

(cat << EOF) > $MAKEFILE
# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
# vendor/htc/shooter/proprietary/*
PRODUCT_COPY_FILES += \\
	vendor/samsung/quincydcm/proprietary/system/lib/libacdbloader.so:obj/lib/libacdbloader.so \\
	vendor/samsung/quincydcm/proprietary/system/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \\
	vendor/samsung/quincydcm/proprietary/system/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

# Adreno200
PRODUCT_COPY_FILES += \\
	vendor/qcom/adreno200/system/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \\
	vendor/qcom/adreno200/system/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \\
	vendor/qcom/adreno200/system/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \\
	vendor/qcom/adreno200/system/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \\
	vendor/qcom/adreno200/system/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \\
	vendor/qcom/adreno200/system/lib/egl/libplayback_adreno200.so:system/lib/egl/libplayback_adreno200.so \\
	vendor/qcom/adreno200/system/lib/libgsl.so:system/lib/libgsl.so \\
	vendor/qcom/adreno200/system/lib/libC2D2.so:system/lib/libC2D2.so \\
	vendor/qcom/adreno200/system/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \\
	vendor/qcom/adreno200/system/lib/libOpenCL.so:system/lib/libOpenCL.so \\
	vendor/qcom/adreno200/system/lib/libOpenVG.so:system/lib/libOpenVG.so \\
	vendor/qcom/adreno200/system/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \\
	vendor/qcom/adreno200/system/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \\
	vendor/qcom/adreno200/system/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \\
	vendor/qcom/adreno200/system/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \\
	vendor/qcom/adreno200/system/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw

PRODUCT_COPY_FILES += \\
EOF

LINEEND=" \\"
COUNT=`wc -l proprietary-files.txt | awk {'print $1'}`
DISM=`egrep -c '(^#|^$)' proprietary-files.txt`
COUNT=`expr $COUNT - $DISM`
for FILE in `egrep -v '(^#|^$)' proprietary-files.txt`; do
  COUNT=`expr $COUNT - 1`
  if [ $COUNT = "0" ]; then
    LINEEND=""
  fi
  echo "  $OUTDIR/proprietary/system/$FILE:/system/$FILE$LINEEND" >> $MAKEFILE
done
echo "  $OUTDIR/proprietary/system/lib/hw/sensors.msm8660.so:/system/lib/hw/sensors.msm8660.so$LINEEND" >> $MAKEFILE

(cat << EOF) > ../../../$OUTDIR/$DEVICE-vendor.mk
# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/$VENDOR/$DEVICE/overlay

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
EOF

(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
EOF
